# -*- coding: utf-8 -*-
"""Python Work

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10INs0-Ls5Plmo_8EjlVPvH71iu0gYKOO

Test Printing
"""

print("Hello, world!")

"""Name Query Test"""

Name = input("What is your name? ")
print("Hello, " + Name)

"""Name & Age Query Test"""

FirstName, LastName, Age = input("What is your first name? "), input("What is your last name? "), input("What is your current age? ")
print("Hello, ", FirstName, LastName, "\n Your current age is: ", Age)

"""BMI Calculator"""

#Simple BMI Calculator
FirstName = input("What is your first name? ")
LastName = input("What is your last name? ")
Age = input("What is your current age? ")
Weight = int(input("What is your current weight? "))
Height = int(input("What is your height(in inches)? "))

# To calculate BMI correctly for height in meters, make sure to convert height from centimeters to meters
BMI = (Weight / (Height)**2) * 703
#BMI = float(BMI)

print("Hello,", FirstName, LastName)
print("Your current age is:", Age)
print("Your current BMI is:", round(BMI, 2))

"""Test Checker using El-If Statements"""

#Basic test checker program
#Get user test score
Score = int(input("Please enter your test score: "))
if Score > 100:
  print("Error, this score is greater than 100")
elif Score == 100:
  print("You have an A++")
elif Score <= 99 and Score >= 97:
  print("You have an A+")
elif Score <= 96 and Score >= 94:
  print("You have an A")
elif Score <= 93 and Score >= 90:
  print("You have an A-")
elif Score <= 89 and Score >= 87:
  print("You have a B+")
elif Score <= 86 and Score >= 84:
  print("You have a B")
elif Score <= 83 and Score >= 80:
  print("You have a B-")
elif Score <= 79 and Score >= 77:
  print("You have a C+")
elif Score <= 76 and Score >= 74:
  print("You have a C")
elif Score <= 73 and Score >= 70:
  print("You have a C-")
elif Score <= 69 and Score >= 65:
  print("You have a D+")
elif Score <= 64 and Score >= 0:
  print("You failed! ")
elif Score < 0:
  print("Error, this score is less than 0")
else:
  print("Try again")

print("Thanks for participating!")

"""Same program as above using an Error Catcher"""

#Basic test checker program with error handling
#Get user test score

while True:
    try:
        Score = int(input("Please enter your test score: "))
        # Exit if true
        break
    except ValueError:
        print("The input was not a valid number.")

#Get user test score
if Score > 100:
  print("Error, this score is greater than 100")
elif Score == 100:
  print("You have an A++")
elif Score <= 99 and Score >= 97:
  print("You have an A+")
elif Score <= 96 and Score >= 94:
  print("You have an A")
elif Score <= 93 and Score >= 90:
  print("You have an A-")
elif Score <= 89 and Score >= 87:
  print("You have a B+")
elif Score <= 86 and Score >= 84:
  print("You have a B")
elif Score <= 83 and Score >= 80:
  print("You have a B-")
elif Score <= 79 and Score >= 77:
  print("You have a C+")
elif Score <= 76 and Score >= 74:
  print("You have a C")
elif Score <= 73 and Score >= 70:
  print("You have a C-")
elif Score <= 69 and Score >= 65:
  print("You have a D+")
elif Score <= 64 and Score >= 0:
  print("You failed! ")
elif Score < 0:
  print("Error, this score is less than 0")
else:
  print("Try again")

print("Thanks for participating!")